2017-06-04 12:52:53,434 INFO PYTHON ERRORS:
 Main FunctionTraceback Info:
  File "/home/geonode/Documents/Python/Interpolation_indexing.py", line 138, in interpolate
    arrRadar2 = arrRadar*arrCloudCopy +999.

Error Info:
    <class 'bdb.BdbQuit'>: 

2017-06-04 12:52:53,434 INFO PYTHON ERRORS:
 Main FunctionTraceback Info:
  File "/home/geonode/Documents/Python/Interpolation_indexing.py", line 138, in interpolate
    arrRadar2 = arrRadar*arrCloudCopy +999.

Error Info:
    <class 'bdb.BdbQuit'>: 

2017-06-04 13:12:28,051 INFO PYTHON ERRORS:
 Main FunctionTraceback Info:
  File "/home/geonode/Documents/Python/Interpolation_indexing.py", line 138, in interpolate
    arrRadar2 = arrRadar*arrCloudCopy

Error Info:
    <class 'bdb.BdbQuit'>: 

2017-06-04 13:12:28,051 INFO PYTHON ERRORS:
 Main FunctionTraceback Info:
  File "/home/geonode/Documents/Python/Interpolation_indexing.py", line 138, in interpolate
    arrRadar2 = arrRadar*arrCloudCopy

Error Info:
    <class 'bdb.BdbQuit'>: 

2017-06-04 13:15:28,525 INFO PYTHON ERRORS:
 Main FunctionTraceback Info:
  File "/home/geonode/Documents/Python/Interpolation_indexing.py", line 145, in interpolate
    print datetime.now().strftime("-%y-%m-%d_%H-%M-%S")

Error Info:
    <class 'bdb.BdbQuit'>: 

2017-06-04 13:15:28,525 INFO PYTHON ERRORS:
 Main FunctionTraceback Info:
  File "/home/geonode/Documents/Python/Interpolation_indexing.py", line 145, in interpolate
    print datetime.now().strftime("-%y-%m-%d_%H-%M-%S")

Error Info:
    <class 'bdb.BdbQuit'>: 

2017-06-05 07:15:42,362 INFO PYTHON ERRORS:
 Main FunctionTraceback Info:
  File "/home/geonode/Documents/Python/Interpolation_indexing.py", line 158, in interpolate
    returnList = makeSpiralSearchinMatrix(arrRadar2,m,n,100,DN_value_optical_image)# for now the threshold is 3 pixels

Error Info:
    <class 'bdb.BdbQuit'>: 

2017-06-05 07:15:42,362 INFO PYTHON ERRORS:
 Main FunctionTraceback Info:
  File "/home/geonode/Documents/Python/Interpolation_indexing.py", line 158, in interpolate
    returnList = makeSpiralSearchinMatrix(arrRadar2,m,n,100,DN_value_optical_image)# for now the threshold is 3 pixels

Error Info:
    <class 'bdb.BdbQuit'>: 

2017-06-05 07:25:35,377 INFO PYTHON ERRORS:
 Main FunctionTraceback Info:
  File "/home/geonode/Documents/Python/Interpolation_indexing.py", line 155, in interpolate
    DN_value_optical_image = arrRadar.item(m,n) #Get DN value from radar image

Error Info:
    <class 'Queue.Empty'>: 

2017-06-05 07:25:35,377 INFO PYTHON ERRORS:
 Main FunctionTraceback Info:
  File "/home/geonode/Documents/Python/Interpolation_indexing.py", line 155, in interpolate
    DN_value_optical_image = arrRadar.item(m,n) #Get DN value from radar image

Error Info:
    <class 'Queue.Empty'>: 

2017-06-05 07:29:31,070 INFO PYTHON ERRORS:
 Main FunctionTraceback Info:
  File "/home/geonode/Documents/Python/Interpolation_indexing.py", line 160, in interpolate
    returnList = makeSpiralSearchinMatrix(arrRadar2,m,n,100,DN_value_optical_image)# for now the threshold is 3 pixels

Error Info:
    <class 'bdb.BdbQuit'>: 

2017-06-05 07:29:31,070 INFO PYTHON ERRORS:
 Main FunctionTraceback Info:
  File "/home/geonode/Documents/Python/Interpolation_indexing.py", line 160, in interpolate
    returnList = makeSpiralSearchinMatrix(arrRadar2,m,n,100,DN_value_optical_image)# for now the threshold is 3 pixels

Error Info:
    <class 'bdb.BdbQuit'>: 

